name: cat_test_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.0
  http: 0.13.3
  shared_preferences: 2.0.6
  loader_overlay: 2.0.2
  flutter_spinkit: 5.0.0
  infinite_scroll_pagination: 3.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

